### ISSUE TITLE
liens tumblr dane le menu

### ISSUE THREAD

**Issue by jg-you** [olivierdeserres/olivierdeserres.github.io#12]
(Ol veut un lien vers sont tumbler qqe part)

**Comment by louisroy** [comment]
J'ai ajouté deux <li> après la loop qui génére le menu.

Je suggère que ça soit deux items statiques qu'ils puissent pas changer.

Pis j'en ai profité pour remplacer ça par des beaux icônes d'envelope, pis du logo Tumblr.

**Comment by jg-you** [comment]
Pourrait être direct dans le template ouais. a+

**Comment by jg-you** [comment]
Le generateur est arrangé pour ça maintenant
