### ISSUE TITLE
PhotoSwipe : a is undefined

### ISSUE THREAD

**Issue by louisroy** [olivierdeserres/olivierdeserres.github.io#14]
Le ```<div>``` qui contient le PhotoSwipe était pas outputté dans la page, donc ça pouvait pas marcher.

J'ai remarqué qu'il était placé à l'extérieur du block CONTENT dans picture_page.tpl. Faq je l'ai redéplacé à l'intérieur.

Je te l'assigne parce que je sais pas encore si ça va se compiler comme du monde. J'ai pas checké encore comment déclencher ça de mon bord.

**Comment by jg-you** [comment]
C'est pour ça que ça marchait pas en effet
pictue-page.tpl hérite de base-page.tpl et remplace les blocs CONTENT_NAV et CONTENT par ce qui est contenu entre {%%}{%%}.
