### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by jg-you** [olivierdeserres/olivierdeserres.github.io#16]
Le tiling est bizarre quand le site load.
Ça s'arrange tu?

**Comment by jg-you** [comment]
Je fais le message de mes vieilles issues. Est-ce que ça se règle facilement @louisroy?

**Comment by louisroy** [comment]
One year old issue, ça brasse. Pour moi c'est un non-issue, c'est une question de fraction de seconde avant que ça se place.
