### ISSUE TITLE
Procédure

### ISSUE THREAD

**Issue by louisroy** [olivierdeserres/olivierdeserres.github.io#6]
Est-ce que t'as un petit walkthrough pour générer les fichiers statiques ou t'es pas rendu là encore?

J'ai updaté une couple d'affaires dans le design pis j'aimerais ça migré ça dans les templates et voir le résultat final mais je sais pas trop comment m'y prendre avec le Dropbox et tout.

Et ça serait pas mauvais de le documenter dans le README aussi.

**Comment by jg-you** [comment]
Update: je vais rajouter un petit script .bat (côté ol, i.e Dropbox/Olivierdesserres) pour déclencher le watcher et donc un update
